### ISSUE TITLE
install build error

### ISSUE THREAD

**Issue by dvbit** [weweave/landroid-bridge#10]
1st thanks for the development!
I am trying to install from source on latest debian on pc but it fails.
This is the log

I have tried to understand but I am not a devel :-(

5894 silly extract meow@3.7.0
5895 silly tarball trying meow@^3.3.0 by hash: sha1-cstmi0JSKCkKu/qFaJJYcwioAfs=
5896 silly tarball no local data for meow@^3.3.0. Extracting by manifest.
5897 http fetch GET 200 https://registry.npmjs.org/error/-/error-7.0.2.tgz 661ms
5898 silly extract error@^7.0.0 extracted to /home/reinan/landroid-bridge/node_modules/.staging/error-f591077e (664ms)
5899 silly extract read-pkg-up@1.0.1
5900 silly tarball trying read-pkg-up@^1.0.1 by hash: sha1-nWPBMnbAZZGNV/ACpX9AobZD+wI=
5901 silly tarball no local data for read-pkg-up@^1.0.1. Extracting by manifest.
5902 http fetch GET 200 https://registry.npmjs.org/csproj2ts/-/csproj2ts-1.1.0.tgz 757ms
5903 silly extract csproj2ts@^1.1.0 extracted to /home/reinan/landroid-bridge/node_modules/.staging/csproj2ts-4fb410b9 (759ms)
5904 silly extract read-pkg@1.1.0
5905 silly tarball trying read-pkg@^1.0.0 by hash: sha1-9f+qXs0pyzHAR0vKfXVra7KePyg=
5906 silly tarball no local data for read-pkg@^1.0.0. Extracting by manifest.
5907 http fetch GET 200 https://registry.npmjs.org/grunt-tslint/-/grunt-tslint-5.0.2.tgz 1099ms
5908 silly extract grunt-tslint@^5.0.2 extracted to /home/reinan/landroid-bridge/node_modules/.staging/grunt-tslint-239936c6 (1117ms)
5909 silly extract normalize-package-data@2.4.0
5910 silly tarball trying normalize-package-data@^2.3.4 by hash: sha512-9jjUFbTPfEy3R/ad/2oNbKtW9Hgovl5O1FvFWKkKblNXoN/Oou6+9+KKohPK13Yc3/TyunyWhJp6gvRNR/PPAw==
5911 silly tarball no local data for normalize-package-data@^2.3.4. Extracting by manifest.
5912 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
5912 verbose stack     at writeAfterEnd (_stream_writable.js:241:12)
5912 verbose stack     at PassThrough.Writable.write (_stream_writable.js:291:5)
5912 verbose stack     at PassThrough.Writable.end (_stream_writable.js:576:10)
5912 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
5912 verbose stack     at ReadEntry.emit (events.js:185:15)
5912 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
5912 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
5912 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
5912 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
5912 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
5912 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
5912 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
5912 verbose stack     at Unzip.emit (events.js:180:13)
5912 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
5912 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
5912 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
5913 verbose cwd /home/reinan/landroid-bridge
5914 verbose Linux 4.9.0-6-amd64
5915 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
5916 verbose node v9.11.1
5917 verbose npm  v6.0.1
5918 error code ERR_STREAM_WRITE_AFTER_END
5919 error write after end
5920 verbose exit [ 1, true ]

**Comment by virtualzone** [comment]
Hi @dvbit , there seems to be an error when extracting one of the NPM dependencies. Please try to delete the node_modules folder and run "npm install" again.

**Comment by dvbit** [comment]
did that.
npm install as root orwith sudo
same result :-(
5819 silly extract glob@~7.0.0 extracted to /home/reinan/landroid-bridge/node_modules/.staging/glob-78ea616a (88ms)
5820 silly extract callback-stream@1.1.0
5821 silly extract mqtt-packet@5.6.0
5822 silly extract bl@1.2.2
5823 silly tarball trying callback-stream@^1.0.2 by hash: sha1-RwGlEmbwbgbqpx/BcjOCLYdfSQg=
5824 silly tarball trying mqtt-packet@^5.6.0 by hash: sha512-QECe2ivqcR1LRsPobRsjenEKAC3i1a5gmm+jNKJLrsiq9PaSQ18LlKFuxvhGxWkvGEPadWv6rKd31O4ICqS1Xw==
5825 silly tarball trying bl@^1.2.1 by hash: sha512-e8tQYnZodmebYDWGH7KMRvtzKXaJHx3BbilrgZCfvyLUYdKpK1t5PSPmpkny/SgiTSCnjfLW7v5rlONXVFkQEA==
5826 silly extract error@^7.0.0 extracted to /home/reinan/landroid-bridge/node_modules/.staging/error-f591077e (122ms)
5827 silly extract inflight@^1.0.4 extracted to /home/reinan/landroid-bridge/node_modules/.staging/inflight-ce133e1e (51ms)
5828 silly extract end-of-stream@^1.4.1 extracted to /home/reinan/landroid-bridge/node_modules/.staging/end-of-stream-07338a78 (51ms)
5829 silly extract once@^1.4.0 extracted to /home/reinan/landroid-bridge/node_modules/.staging/once-1373ee2a (50ms)
5830 silly extract readable-stream@2.3.6
5831 silly extract util-deprecate@1.0.2
5832 silly extract raw-body@2.3.3
5833 silly extract finalhandler@1.1.1
5834 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
5834 verbose stack     at writeAfterEnd (_stream_writable.js:241:12)
5834 verbose stack     at PassThrough.Writable.write (_stream_writable.js:291:5)
5834 verbose stack     at PassThrough.Writable.end (_stream_writable.js:576:10)
5834 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
5834 verbose stack     at ReadEntry.emit (events.js:185:15)
5834 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
5834 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
5834 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
5834 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
5834 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
5834 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
5834 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
5834 verbose stack     at Unzip.emit (events.js:180:13)
5834 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
5834 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
5834 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
5835 verbose cwd /home/reinan/landroid-bridge
5836 verbose Linux 4.9.0-6-amd64
5837 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
5838 verbose node v9.11.1
5839 verbose npm  v6.0.1
5840 error code ERR_STREAM_WRITE_AFTER_END
5841 error write after end
5842 verbose exit [ 1, true ]
