### ISSUE TITLE
npm installl error

### ISSUE THREAD

**Issue by webcharlyx** [weweave/landroid-bridge#20]
**first of all thanks for the great interface!**
Im no dev, so I hope to get help here.
I already had landroid-bridge successfully running by installation from source, but after dist update I received a missing java module error, so I tried git pull and npm update.
update compilation had errors, so I backed up the config.json, removed all install dir and tried with complete new installation. This now fails with:
```
$ npm install
(node:12697) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json landroid-bridge@0.1.0 No repository field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/lib/landroid-bridge
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/landroid-bridge/npm-debug.log
npm ERR! not ok code 0
```
[npm-debug.log](https://github.com/weweave/landroid-bridge/files/2204815/npm-debug.log)

I cant understand 638 error Error: Method Not Allowed
Somewhere i saw npm to be expected in version >=3.0.0. on this system it is only 1.4.21. might this be causing?

**Comment by webcharlyx** [comment]
not yet solved.
successfully using docker image instead.
