### ISSUE TITLE
WeatherRouter - TypeError: Cannot read property 'loadHistory' of undefined

### ISSUE THREAD

**Issue by webcharlyx** [weweave/landroid-bridge#21]
using latest docker image: schematic does not show any contents and in Log i found:
```
at onLoaded (/usr/src/app/dist/WeatherWunderground.js:136:22)
    at Promise (/usr/src/app/dist/WeatherWunderground.js:188:21)
    at new Promise (<anonymous>)
    at WeatherWunderground.loadHourly10day (/usr/src/app/dist/WeatherWunderground.js:179:16)
    at WeatherRouter.getHourly10DayForcast (/usr/src/app/dist/WeatherRouter.js:15:55)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
```
[landroid-bridge_WU-LoadHistory-fail.txt](https://github.com/weweave/landroid-bridge/files/2209493/landroid-bridge_WU-LoadHistory-fail.txt)

on WU i use the former free api account

**Comment by virtualzone** [comment]
Thanks for your bug report, @webcharlyx! The latest commit should fix it. Could you please verify it's working now?
