### ISSUE TITLE
App - Unhandled exception: TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by k3erg** [weweave/landroid-bridge#38]
Since two days I got this error ... any hints on debugging options?

```
xxx@yyy:~/landroid-bridge $ node dist/server.js
[2018-10-02T09:25:15.110] [INFO] server.ts - Starting Landroid Bridge...
[2018-10-02T09:25:15.122] [INFO] server.ts - Setting port to 3000...
[2018-10-02T09:25:15.347] [INFO] Mqtt - Connecting to MQTT Broker...
[2018-10-02T09:25:15.390] [INFO] App - Adding static files path /home/pi/landroid-bridge/www
[2018-10-02T09:25:15.392] [INFO] Scheduler - Skipping scheduler initialization (not enabled)
[2018-10-02T09:25:15.408] [INFO] LandroidS - Initializing Landroid Cloud Service...
[2018-10-02T09:25:15.414] [WARN] IoBrokerAdapter - landroid-cloud-2.js will be replaced in next version by mqttCloud.js and worxConfig.js. Reason: better handling of models and mqttCloud supports more brands by a diffent config see also: https://www.npmjs.com/package/iobroker.kress
[2018-10-02T09:25:15.611] [INFO] Mqtt - Successfully connected to MQTT Broker!
[2018-10-02T09:25:15.981] [INFO] IoBrokerAdapter - Logged in as xxx@yyy.zzz API Token Set to : XXX
[2018-10-02T09:25:16.555] [INFO] IoBrokerAdapter - mower 0 selected
[2018-10-02T09:25:16.556] [INFO] IoBrokerAdapter - DB510
[2018-10-02T09:25:16.858] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
[2018-10-02T09:25:18.111] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
[2018-10-02T09:25:19.358] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
[2018-10-02T09:25:20.591] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
[2018-10-02T09:25:21.826] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
...
^C[2018-10-02T09:25:54.748] [INFO] App - Received exit signal...
[2018-10-02T09:25:54.749] [INFO] App - Closing http listener...
```

**Comment by berland** [comment]
Same problem, Ubuntu 16.04.

**Comment by sracing** [comment]
I´m having the same issue, which prevents the landroid-bridge from connecting to the broker. Is there any solution to that?

**Comment by MatziBrow** [comment]
I have the same problem. The generated network traffic leads to significant instability of the whole network. I tried several things in order to identify the root cause, but I was not successful.

Could someone look into this?

**Comment by ciechompl** [comment]
reopening issue ... 
Today I pulled the latest repo, build docker container from the scratch and got this error" 

`
[2020-04-15T19:54:22.120] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/iobroker.landroid-s/lib/mqttCloud.js:240:22)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

with previous repo I had issues with connection but never those.
Anyone any idea how to fix it ?

**Comment by kaareseras** [comment]
I get the same error, both from building from source, or running the docker

[32m[2020-04-15T22:12:37.933] [INFO] server.ts - [39mStarting Landroid Bridge...
[32m[2020-04-15T22:12:37.938] [INFO] server.ts - [39mSetting port to 3000...
[32m[2020-04-15T22:12:37.983] [INFO] Mqtt - [39mConnecting to MQTT Broker...
[32m[2020-04-15T22:12:37.984] [INFO] App - [39mAdding static files path C:\GitHub\landroid-bridge\www
[32m[2020-04-15T22:12:37.985] [INFO] Scheduler - [39mSkipping scheduler initialization (not enabled)
[32m[2020-04-15T22:12:37.989] [INFO] LandroidS - [39mInitializing Landroid Cloud Service...
[91m[2020-04-15T22:12:38.027] [ERROR] App - [39mUnhandled exception: TypeError: Cannot read property 'log' of undefined
[32m[2020-04-15T22:12:38.032] [INFO] Mqtt - [39mSuccessfully connected to MQTT Broker!
[32m[2020-04-15T22:13:37.990] [INFO] LandroidS - [39mCould not finish initialization, retrying...
[91m[2020-04-15T22:13:38.025] [ERROR] App - [39mUnhandled exception: TypeError: Cannot read property 'log' of undefined
[32m[2020-04-15T22:14:37.991] [INFO] LandroidS - [39mCould not finish initialization, retrying...
[91m[2020-04-15T22:14:37.996] [ERROR] App - [39mUnhandled exception: TypeError: Cannot read property 'log' of undefined
