### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by JimboJones3101** [weweave/landroid-bridge#49]
Hi there,

I know it's not a problem of this solution, but still I cannot figure out how to proceed.

I cloned the directory and ran `sudo npm install`

This is what I got:

> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/openhabian/landroid-bridge/node_modules/sqlite3/lib/binding/node-v67-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/openhabian/landroid-bridge/node_modules/sqlite3/lib/binding/node-v67-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/openhabian/landroid-bridge/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1001:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
> node-pre-gyp ERR! System Linux 4.14.98-v7+
> node-pre-gyp ERR! command "/usr/bin/node" "/home/openhabian/landroid-bridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/openhabian/landroid-bridge/node_modules/sqlite3
> node-pre-gyp ERR! node -v v11.13.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/openhabian/landroid-bridge/node_modules/sqlite3/lib/binding/node-v67-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/openhabian/landroid-bridge/node_modules/sqlite3/lib/binding/node-v67-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
> npm WARN landroid-bridge@0.1.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sqlite3@4.0.6 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-04-13T19_44_35_480Z-debug.log

Any idea how to proceed?

**Comment by JimboJones3101** [comment]
Issue can be closed. Figured out how to deal with the problem.

Issue was that there was no sqlite3 folder in node_modules. Even after deleting the folder and rebuilding everything it was not there. Fortunately I had anothe nodeJS application running which had this folder. I copied it to the landroid-bridge repository reran install and voila. Install worked!

**Comment by JimboJones3101** [comment]
Issue closed
