### ISSUE TITLE
Missing node_sqlite3.node 

### ISSUE THREAD

**Issue by Billiboy71** [weweave/landroid-bridge#62]
I have Build from Source
Run: npm run grunt 
Error:
`Running "tslint:files" (tslint) task
>> 17 files lint free.

Running "ts:app" (ts) task
Compiling...
Using tsc v3.4.5
>> Warning: created src/.baseDir.ts file because `outDir` was specified in the Gruntfile ts `options`, but not `rootDir`.  Add `rootDir`  under the task or target `options` object to fix this warning.

TypeScript compilation complete: 21.77s for 18 TypeScript files.

Done.
`
Update config.json to match your environment and then 

node dist/server.js

Error
`pi@homebridge:~/landroid-bridge $ node dist/server.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/landroid-bridge/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/landroid-bridge/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`

Can someone help?

**Comment by sracing** [comment]
I can confirm there is a issue with a clean Raspberry ARMv6 install by using nodejs 8.11.1. I am getting the same error during sqlite 3 installation routine.

**Comment by Billiboy71** [comment]
i have use this an it run
wget https://nodejs.org/dist/v8.9.0/node-v8.9.0-linux-armv7l.tar.gz
tar -xzf node-v8.9.0-linux-armv7l.tar.gz
cd node-v8.9.0-linux-armv7l/
sudo cp -R * /usr/local/bin

**Comment by Billiboy71** [comment]
and sudo apt-get install libsqlite3-dev
npm install sqlite3 --build-from-source --sqlite=/usr

**Comment by WWebber** [comment]
I wonder, why you not use a newer nodeJS? I e.g. installed 10.15.3.armv7 and everything runs smoothly on a raspi3. The only issue I had, was that I launched the wrong "nodeJS" from a wrong path.

**Comment by InvertedMinor** [comment]
Hi had the same issue, upgrading Node 10.16.0 LTS to Node.js 12.4.0 solved the missing node_sqlite3.node
